"""PlanManager — lightweight planning primitives for orchestrator mode."""

from __future__ import annotations

from typing import Any

from langchain_core.messages import BaseMessage, HumanMessage

from smartclaw.agent.orchestration_models import TodoItem, TodoPlan, todo_identifier
from smartclaw.capabilities.registry import CapabilityPackRegistry
from smartclaw.steps.registry import StepRegistry

_INTENT_KEYWORDS: dict[str, tuple[str, ...]] = {
    "inspection": ("检查", "巡检", "审计", "基线", "弱口令", "scan", "audit", "inspect", "review"),
    "remediation": ("整改", "修复", "加固", "hardening", "remediate", "remediation", "fix", "patch"),
    "reporting": ("报告", "汇总", "总结", "输出", "report", "summary", "deliverable"),
    "analysis": ("需求", "分析", "requirement", "analysis"),
    "design": ("设计", "接口", "api", "contract", "schema"),
    "documentation": ("文档", "doc", "documentation"),
}
_EXECUTION_KEYWORDS = ("执行", "应用", "apply", "实施", "落地", "修改", "变更", "修复", "加固", "patch", "fix")
_VALID_PLAN_ROLES = {"core", "conditional", "terminal"}
_VALID_ACTIVATION_MODES = {"immediate", "after_artifact", "approval_gated"}
_VALID_DISPLAY_POLICIES = {"always_show", "show_when_ready"}


class PlanManager:
    """Create and update coarse-grained execution plans."""

    def __init__(
        self,
        *,
        step_registry: StepRegistry | None = None,
        capability_registry: CapabilityPackRegistry | None = None,
        capability_pack: str | None = None,
    ) -> None:
        self._step_registry = step_registry
        self._capability_registry = capability_registry
        self._capability_pack = capability_pack

    def create_initial_plan(
        self,
        messages: list[BaseMessage],
        *,
        artifacts: list[dict[str, Any]] | None = None,
        current_plan: TodoPlan | None = None,
    ) -> TodoPlan:
        """Build an initial plan from the latest user message."""
        objective = self._extract_objective(messages)
        todos = self._infer_todos(objective, artifacts=artifacts, current_plan=current_plan)
        todos = self._reconcile_dependencies(todos)
        return {
            "plan_version": "v1",
            "objective": objective,
            "strategy": "rule_based_fallback",
            "missing_inputs": [],
            "reasoning_summary": "Generated by the fallback rule planner.",
            "todos": todos,
        }

    def replan(
        self,
        messages: list[BaseMessage],
        *,
        artifacts: list[dict[str, Any]] | None = None,
        current_plan: TodoPlan | None = None,
    ) -> TodoPlan:
        """Build a fallback replanned TodoPlan constrained by current artifacts and terminal steps."""
        objective = self._extract_objective(messages)
        todos = self._infer_todos(objective, artifacts=artifacts, current_plan=current_plan)
        todos = self._reconcile_dependencies(todos)
        return {
            "plan_version": "v1",
            "objective": objective,
            "strategy": "rule_based_replan",
            "missing_inputs": [],
            "reasoning_summary": "Generated by the fallback rule replanner.",
            "todos": todos,
        }

    def mark_plan_completed(self, plan: TodoPlan | None) -> TodoPlan | None:
        """Return *plan* with all todos marked completed."""
        if plan is None:
            return None
        completed_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            updated["status"] = "completed"
            completed_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = completed_todos
        return updated_plan  # type: ignore[return-value]

    def apply_results(
        self,
        plan: TodoPlan | None,
        task_results: list[dict[str, Any]] | None,
    ) -> TodoPlan | None:
        """Update todo status based on normalized task results."""
        if plan is None:
            return None
        results_by_id = {
            str(result["todo_id"]): result
            for result in (task_results or [])
            if isinstance(result, dict) and result.get("todo_id")
        }
        updated_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            result = results_by_id.get(todo_identifier(updated))
            if result is not None:
                updated["status"] = "completed" if result.get("status") == "completed" else "failed"
            updated_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = updated_todos
        return self.refresh_ready_todos(updated_plan)

    def refresh_ready_todos(self, plan: TodoPlan | None) -> TodoPlan | None:
        """Promote pending todos whose dependencies are satisfied."""
        if plan is None:
            return None

        statuses = {todo_identifier(todo): todo["status"] for todo in plan["todos"]}
        refreshed_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            if updated["status"] in {"completed", "failed", "cancelled", "in_progress", "pending_approval"}:
                refreshed_todos.append(updated)  # type: ignore[arg-type]
                continue

            dependency_ids = [str(dep_id) for dep_id in updated.get("depends_on", [])]
            if not dependency_ids:
                updated["status"] = "ready"
            else:
                dependency_states = [statuses.get(dep_id, "failed") for dep_id in dependency_ids]
                if any(state in {"failed", "cancelled", "blocked"} for state in dependency_states):
                    updated["status"] = "blocked"
                elif all(state == "completed" for state in dependency_states):
                    updated["status"] = "ready"
                else:
                    updated["status"] = "pending"
            refreshed_todos.append(updated)  # type: ignore[arg-type]

        updated_plan = dict(plan)
        updated_plan["todos"] = refreshed_todos
        return updated_plan  # type: ignore[return-value]

    def mark_todos_in_progress(
        self,
        plan: TodoPlan | None,
        todo_ids: list[str],
    ) -> TodoPlan | None:
        """Mark the selected ready todos as in progress."""
        if plan is None:
            return None
        selected = set(todo_ids)
        updated_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            if todo_identifier(updated) in selected and updated["status"] == "ready":
                updated["status"] = "in_progress"
            updated_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = updated_todos
        return updated_plan  # type: ignore[return-value]

    def mark_todos_pending_approval(
        self,
        plan: TodoPlan | None,
        todo_ids: list[str],
    ) -> TodoPlan | None:
        """Mark selected todos as waiting for explicit approval."""
        if plan is None:
            return None
        selected = set(todo_ids)
        updated_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            if todo_identifier(updated) in selected and updated["status"] in {"ready", "pending", "in_progress"}:
                updated["status"] = "pending_approval"
            updated_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = updated_todos
        return updated_plan  # type: ignore[return-value]

    def skip_pending_approval_todos(
        self,
        plan: TodoPlan | None,
        todo_ids: list[str],
    ) -> TodoPlan | None:
        """Cancel approval-gated todos and relax downstream dependencies.

        This is used for choices such as "report only" where the user wants to
        skip mutation steps but still continue the orchestrator with read-only
        or reporting work.
        """
        if plan is None:
            return None
        selected = set(todo_ids)
        updated_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            todo_id = todo_identifier(updated)
            if todo_id in selected and updated["status"] in {"ready", "pending", "in_progress", "pending_approval"}:
                updated["status"] = "cancelled"
            depends_on = [str(dep_id) for dep_id in updated.get("depends_on", [])]
            if depends_on:
                updated["depends_on"] = [dep_id for dep_id in depends_on if dep_id not in selected]
            updated_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = updated_todos
        return self.refresh_ready_todos(updated_plan)

    def approve_pending_todos(
        self,
        plan: TodoPlan | None,
        todo_ids: list[str],
    ) -> TodoPlan | None:
        """Promote pending-approval todos back into the runnable queue."""
        if plan is None:
            return None
        selected = set(todo_ids)
        updated_todos: list[TodoItem] = []
        for todo in plan["todos"]:
            updated = dict(todo)
            if todo_identifier(updated) in selected and updated["status"] == "pending_approval":
                updated["status"] = "pending"
            updated_todos.append(updated)  # type: ignore[arg-type]
        updated_plan = dict(plan)
        updated_plan["todos"] = updated_todos
        return self.refresh_ready_todos(updated_plan)

    def get_ready_todos(self, plan: TodoPlan | None) -> list[TodoItem]:
        """Return todos that are ready for dispatch."""
        if plan is None:
            return []
        return [todo for todo in plan["todos"] if todo["status"] == "ready"]

    def has_pending_approval(self, plan: TodoPlan | None) -> bool:
        """Return True when at least one todo is waiting for approval."""
        if plan is None:
            return False
        return any(todo["status"] == "pending_approval" for todo in plan["todos"])

    def is_plan_completed(self, plan: TodoPlan | None) -> bool:
        """Return True when all todos are completed."""
        return bool(plan and plan["todos"] and all(todo["status"] == "completed" for todo in plan["todos"]))

    def has_remaining_work(self, plan: TodoPlan | None) -> bool:
        """Return True when at least one todo still needs processing."""
        if plan is None:
            return False
        return any(
            todo["status"] in {"pending", "pending_approval", "ready", "in_progress", "blocked"}
            for todo in plan["todos"]
        )

    def _extract_objective(self, messages: list[BaseMessage]) -> str:
        for msg in reversed(messages):
            if isinstance(msg, HumanMessage):
                content = msg.content if isinstance(msg.content, str) else str(msg.content)
                return content.strip()
        return ""

    def _infer_todos(
        self,
        objective: str,
        *,
        artifacts: list[dict[str, Any]] | None = None,
        current_plan: TodoPlan | None = None,
    ) -> list[TodoItem]:
        text = objective.strip()
        if not text:
            return []

        registry_todos = self._infer_registry_todos(text, artifacts=artifacts, current_plan=current_plan)
        if registry_todos:
            return registry_todos

        completed_todo_ids = [
            str(todo.get("todo_id"))
            for todo in (current_plan or {}).get("todos", [])
            if isinstance(todo, dict) and str(todo.get("status")) == "completed" and todo.get("todo_id")
        ]
        terminal_step_ids = {
            str(todo.get("step_id"))
            for todo in (current_plan or {}).get("todos", [])
            if isinstance(todo, dict) and str(todo.get("status")) in {"completed", "failed", "cancelled"}
        }
        todos: list[TodoItem] = []

        if (
            "inspect" not in terminal_step_ids
            and any(keyword in text for keyword in ("检查", "巡检", "基线", "弱口令", "firewall", "防火墙"))
        ):
            todos.append(
                self._build_todo(
                    todo_id="inspect",
                    step_id="inspect",
                    title="执行检查任务",
                    kind="inspection",
                    parallelizable=True,
                    depends_on=[],
                )
            )

        if (
            "remediate" not in terminal_step_ids
            and any(keyword in text for keyword in ("根据结果", "加固", "整改", "修复", "hardening"))
        ):
            depends_on = [todo_identifier(todo) for todo in todos] or completed_todo_ids[:1]
            todos.append(
                self._build_todo(
                    todo_id="remediate",
                    step_id="remediate",
                    title="根据检查结果执行整改",
                    kind="remediation",
                    parallelizable=False,
                    depends_on=depends_on[:1],
                )
            )

        if (
            "report" not in terminal_step_ids
            and any(keyword in text for keyword in ("报告", "汇总", "总结", "输出"))
        ):
            deps = [todo_identifier(todo) for todo in todos] or completed_todo_ids or ["execute"]
            todos.append(
                self._build_todo(
                    todo_id="report",
                    step_id="report",
                    title="汇总结果并生成输出",
                    kind="report",
                    parallelizable=False,
                    depends_on=deps,
                )
            )

        if not todos and not terminal_step_ids:
            todos.append(
                self._build_todo(
                    todo_id="execute",
                    step_id="execute",
                    title="执行任务",
                    kind="generic",
                    parallelizable=False,
                    depends_on=[],
                )
            )

        return todos

    def _build_todo(
        self,
        *,
        todo_id: str,
        step_id: str,
        title: str,
        kind: str,
        parallelizable: bool,
        depends_on: list[str],
        resolved_inputs: dict[str, Any] | None = None,
        consumes_artifacts: list[str] | None = None,
        approval_required: bool = False,
        execution_mode: str = "subagent",
        preferred_skill: str = "",
        plan_role: str = "core",
        activation_mode: str = "immediate",
        display_policy: str = "always_show",
    ) -> TodoItem:
        return {
            "todo_id": todo_id,
            "step_id": step_id,
            "title": title,
            "kind": kind,
            "status": "pending" if depends_on else "ready",
            "parallelizable": parallelizable,
            "depends_on": depends_on,
            "resolved_inputs": resolved_inputs or {},
            "consumes_artifacts": consumes_artifacts or [],
            "execution_mode": execution_mode,
            "approval_required": approval_required,
            "preferred_skill": preferred_skill,
            "plan_role": plan_role,  # type: ignore[typeddict-item]
            "activation_mode": activation_mode,  # type: ignore[typeddict-item]
            "display_policy": display_policy,  # type: ignore[typeddict-item]
        }

    def _infer_registry_todos(
        self,
        text: str,
        *,
        artifacts: list[dict[str, Any]] | None,
        current_plan: TodoPlan | None,
    ) -> list[TodoItem]:
        if self._step_registry is None:
            return []

        available_artifact_types = self._available_artifact_types(artifacts)
        completed_step_ids = self._completed_step_ids(current_plan)
        terminal_step_ids = self._terminal_step_ids(current_plan)
        pack = None
        if self._capability_registry is not None and self._capability_pack:
            pack = self._capability_registry.get(self._capability_pack)
        candidate_steps = self._step_registry.get_candidate_steps(
            pack,
            available_artifact_types=available_artifact_types if current_plan is not None else None,
            terminal_step_ids=terminal_step_ids,
        )
        if not candidate_steps:
            return []

        objective_intents = self._extract_objective_intents(text)
        step_map = {
            str(step.get("id")): step
            for step in candidate_steps
            if isinstance(step, dict) and step.get("id")
        }
        if not step_map:
            return []

        selected_step_ids = self._select_initial_step_ids(
            objective=text,
            objective_intents=objective_intents,
            step_map=step_map,
        )
        selected_step_ids = self._exclude_reusable_completed_steps(
            selected_step_ids,
            step_map=step_map,
            current_plan=current_plan,
            artifacts=artifacts,
        )
        expanded_step_ids = self._expand_step_dependencies(
            selected_step_ids,
            step_map=step_map,
            completed_step_ids=completed_step_ids,
            objective_intents=objective_intents,
        )
        ordered_step_ids = self._topological_order_steps(expanded_step_ids, step_map=step_map)

        todos: list[TodoItem] = []
        planned_step_ids = set(ordered_step_ids)
        for step_id in ordered_step_ids:
            todos.append(
                self._build_registry_todo(
                    step_id=step_id,
                    title=self._default_step_title(step_map[step_id]),
                    depends_on=self._resolve_planned_dependencies(
                        step_id,
                        step_map=step_map,
                        planned_step_ids=planned_step_ids,
                    ),
                    artifacts=artifacts,
                )
            )
        return todos

    def _build_registry_todo(
        self,
        *,
        step_id: str,
        title: str,
        depends_on: list[str],
        artifacts: list[dict[str, Any]] | None,
    ) -> TodoItem:
        step = (self._step_registry.get(step_id) or {}) if self._step_registry is not None else {}
        consumes_artifacts = (
            self._step_registry.artifact_ids_for_step(step_id, artifacts)
            if self._step_registry is not None
            else []
        )
        resolved_inputs = {}
        if consumes_artifacts:
            resolved_inputs["artifact_ids"] = list(consumes_artifacts)
        plan_role = self._step_plan_role(step)
        activation_mode = self._step_activation_mode(step, step_id=step_id)
        display_policy = self._step_display_policy(step, plan_role=plan_role)
        return self._build_todo(
            todo_id=step_id,
            step_id=step_id,
            title=title,
            kind=str(step.get("kind", "generic") or "generic"),
            parallelizable=bool(step.get("can_parallel", False)),
            depends_on=depends_on,
            resolved_inputs=resolved_inputs,
            consumes_artifacts=consumes_artifacts,
            approval_required=(
                self._step_registry.approval_required_for_step(step_id)
                if self._step_registry is not None
                else False
            ),
            preferred_skill=str(step.get("preferred_skill", "") or ""),
            plan_role=plan_role,
            activation_mode=activation_mode,
            display_policy=display_policy,
        )

    def _collect_dependency_ids(self, todos: list[TodoItem]) -> list[str]:
        return [todo_identifier(todo) for todo in todos]

    def _available_artifact_types(self, artifacts: list[dict[str, Any]] | None) -> set[str]:
        return {
            str(item.get("artifact_type"))
            for item in (artifacts or [])
            if isinstance(item, dict) and item.get("status") == "ready" and item.get("artifact_type")
        }

    def _completed_step_ids(self, current_plan: TodoPlan | None) -> set[str]:
        return {
            str(todo.get("step_id"))
            for todo in (current_plan or {}).get("todos", [])
            if isinstance(todo, dict) and str(todo.get("status")) == "completed" and todo.get("step_id")
        }

    def _terminal_step_ids(self, current_plan: TodoPlan | None) -> set[str]:
        return {
            str(todo.get("step_id"))
            for todo in (current_plan or {}).get("todos", [])
            if isinstance(todo, dict) and str(todo.get("status")) in {"completed", "failed", "cancelled"}
        }

    def _extract_objective_intents(self, text: str) -> set[str]:
        haystack = text.lower()
        intents: set[str] = set()
        for intent, keywords in _INTENT_KEYWORDS.items():
            if any(keyword in text or keyword in haystack for keyword in keywords):
                intents.add(intent)
        return intents

    def _reusable_completed_step_ids(
        self,
        current_plan: TodoPlan | None,
        *,
        artifacts: list[dict[str, Any]] | None,
        step_map: dict[str, dict[str, Any]],
    ) -> set[str]:
        if current_plan is None:
            return set()
        ready_artifact_types = {
            str(item.get("artifact_type"))
            for item in (artifacts or [])
            if isinstance(item, dict) and item.get("status") == "ready" and item.get("artifact_type")
        }
        reusable: set[str] = set()
        for todo in current_plan.get("todos", []):
            if not isinstance(todo, dict) or str(todo.get("status")) != "completed":
                continue
            step_id = str(todo.get("step_id", "") or "")
            if not step_id or step_id not in step_map:
                continue
            outputs = {
                str(item)
                for item in step_map[step_id].get("outputs", [])
                if str(item)
            }
            if not outputs or outputs & ready_artifact_types:
                reusable.add(step_id)
        return reusable

    def _exclude_reusable_completed_steps(
        self,
        selected_step_ids: set[str],
        *,
        step_map: dict[str, dict[str, Any]],
        current_plan: TodoPlan | None,
        artifacts: list[dict[str, Any]] | None,
    ) -> set[str]:
        reusable = self._reusable_completed_step_ids(current_plan, artifacts=artifacts, step_map=step_map)
        return {step_id for step_id in selected_step_ids if step_id not in reusable}

    def _objective_requests_output(self, text: str, objective_intents: set[str]) -> bool:
        if objective_intents & {"reporting", "documentation"}:
            return True
        lowered = text.lower()
        return any(keyword in text or keyword in lowered for keyword in _INTENT_KEYWORDS["reporting"])

    def _objective_requests_execution(self, text: str) -> bool:
        lowered = text.lower()
        return any(keyword in text or keyword in lowered for keyword in _EXECUTION_KEYWORDS)

    def _step_intent_tags(self, step: dict[str, Any]) -> set[str]:
        explicit = {str(item).strip() for item in step.get("intent_tags", []) if str(item).strip()}
        if explicit:
            return explicit
        tags: set[str] = set()
        haystack = " ".join(
            [
                str(step.get("id", "") or ""),
                str(step.get("kind", "") or ""),
                str(step.get("description", "") or ""),
                " ".join(str(item) for item in step.get("outputs", []) if str(item)),
                " ".join(str(item) for item in step.get("consumes_artifact_types", []) if str(item)),
            ]
        ).lower()
        for intent, keywords in _INTENT_KEYWORDS.items():
            if any(keyword.lower() in haystack for keyword in keywords):
                tags.add(intent)
        if not tags and step.get("kind"):
            tags.add(str(step.get("kind")))
        return tags

    def _step_plan_role(self, step: dict[str, Any]) -> str:
        explicit = str(step.get("plan_role", "") or "").strip().lower()
        if explicit in _VALID_PLAN_ROLES:
            return explicit
        kind = str(step.get("kind", "") or "").strip().lower()
        description = str(step.get("description", "") or "").strip().lower()
        outputs = [str(item).strip().lower() for item in step.get("outputs", []) if str(item).strip()]
        side_effect = str(step.get("side_effect_level", "read_only") or "read_only").strip().lower()
        if (
            kind in {"report", "documentation"}
            or any(token in description for token in ("报告", "总结", "汇总", "文档", "最终输出"))
            or any("report" in token or token.endswith("_doc") or token == "api_doc" for token in outputs)
        ):
            return "terminal"
        if side_effect != "read_only":
            return "conditional"
        return "core"

    def _step_activation_mode(self, step: dict[str, Any], *, step_id: str) -> str:
        explicit = str(step.get("activation_mode", "") or "").strip().lower()
        if explicit in _VALID_ACTIVATION_MODES:
            return explicit
        if self._step_registry is not None and self._step_registry.approval_required_for_step(step_id):
            return "approval_gated"
        consumes = [str(item).strip() for item in step.get("consumes_artifact_types", []) if str(item).strip()]
        return "after_artifact" if consumes else "immediate"

    def _step_display_policy(self, step: dict[str, Any], *, plan_role: str) -> str:
        explicit = str(step.get("display_policy", "") or "").strip().lower()
        if explicit in _VALID_DISPLAY_POLICIES:
            return explicit
        return "always_show" if plan_role in {"core", "terminal"} else "show_when_ready"

    def _default_step_title(self, step: dict[str, Any]) -> str:
        description = str(step.get("description", "") or "").strip()
        return description or str(step.get("id", "") or "执行步骤")

    def _select_initial_step_ids(
        self,
        *,
        objective: str,
        objective_intents: set[str],
        step_map: dict[str, dict[str, Any]],
    ) -> set[str]:
        selected: set[str] = set()
        explicit_output_requested = self._objective_requests_output(objective, objective_intents)
        explicit_execution_requested = self._objective_requests_execution(objective)
        for step_id, step in step_map.items():
            step_intents = self._step_intent_tags(step)
            if not objective_intents or not (step_intents & objective_intents):
                continue
            if self._step_plan_role(step) == "terminal" and not explicit_output_requested:
                continue
            if self._step_activation_mode(step, step_id=step_id) == "approval_gated" and not explicit_execution_requested:
                continue
            selected.add(step_id)

        if not selected:
            for step_id, step in step_map.items():
                if self._step_plan_role(step) == "core" and self._step_activation_mode(step, step_id=step_id) == "immediate":
                    selected.add(step_id)
                    break

        should_show_terminal = bool(selected) and explicit_output_requested
        if should_show_terminal:
            for step_id, step in step_map.items():
                if self._step_plan_role(step) != "terminal":
                    continue
                if step_id not in selected and objective_intents and not (self._step_intent_tags(step) & objective_intents):
                    continue
                if self._step_display_policy(
                    step,
                    plan_role="terminal",
                ) != "always_show":
                    continue
                selected.add(step_id)
        selected = self._prune_generic_terminal_steps(selected, step_map=step_map, objective_intents=objective_intents)
        return selected

    def _prune_generic_terminal_steps(
        self,
        selected_step_ids: set[str],
        *,
        step_map: dict[str, dict[str, Any]],
        objective_intents: set[str],
    ) -> set[str]:
        selected = set(selected_step_ids)
        terminal_ids = [step_id for step_id in selected if self._step_plan_role(step_map[step_id]) == "terminal"]
        if len(terminal_ids) < 2:
            return selected
        specific_terminal_exists = any(
            step_id
            for step_id in terminal_ids
            if "reporting" not in self._step_intent_tags(step_map[step_id]) or len(self._step_intent_tags(step_map[step_id])) > 1
        )
        if not specific_terminal_exists:
            return selected
        for step_id in list(terminal_ids):
            step = step_map[step_id]
            step_intents = self._step_intent_tags(step)
            if step_intents == {"reporting"} and objective_intents - {"reporting"}:
                selected.discard(step_id)
        return selected

    def _expand_step_dependencies(
        self,
        selected_step_ids: set[str],
        *,
        step_map: dict[str, dict[str, Any]],
        completed_step_ids: set[str],
        objective_intents: set[str],
    ) -> set[str]:
        expanded = set(selected_step_ids)
        queue = list(selected_step_ids)
        while queue:
            step_id = queue.pop(0)
            for dependency_id in self._inferred_dependency_step_ids(
                step_id,
                step_map=step_map,
                selected_step_ids=expanded,
                include_conditional=False,
            ):
                if dependency_id in completed_step_ids or dependency_id in expanded or dependency_id not in step_map:
                    continue
                dependency_step = step_map[dependency_id]
                dependency_role = self._step_plan_role(dependency_step)
                dependency_intents = self._step_intent_tags(dependency_step)
                if dependency_role != "core" and not (dependency_intents & objective_intents):
                    continue
                expanded.add(dependency_id)
                queue.append(dependency_id)
        return expanded

    def _resolve_planned_dependencies(
        self,
        step_id: str,
        *,
        step_map: dict[str, dict[str, Any]],
        planned_step_ids: set[str],
    ) -> list[str]:
        dependencies = self._inferred_dependency_step_ids(
            step_id,
            step_map=step_map,
            selected_step_ids=planned_step_ids,
            include_conditional=True,
        )
        return [dep_id for dep_id in dependencies if dep_id in planned_step_ids]

    def _inferred_dependency_step_ids(
        self,
        step_id: str,
        *,
        step_map: dict[str, dict[str, Any]],
        selected_step_ids: set[str],
        include_conditional: bool,
    ) -> list[str]:
        step = step_map.get(step_id) or {}
        explicit = [str(item).strip() for item in step.get("default_depends_on", []) if str(item).strip()]
        if explicit:
            return [dep_id for dep_id in explicit if dep_id in step_map]

        dependency_ids: list[str] = []
        consumes = [str(item).strip() for item in step.get("consumes_artifact_types", []) if str(item).strip()]
        for artifact_type in consumes:
            producers = [
                producer_id
                for producer_id, producer_step in step_map.items()
                if artifact_type in {str(item).strip() for item in producer_step.get("outputs", []) if str(item).strip()}
            ]
            for producer_id in producers:
                if producer_id == step_id:
                    continue
                producer_role = self._step_plan_role(step_map[producer_id])
                if not include_conditional and producer_role == "conditional":
                    continue
                if producer_id not in selected_step_ids and producer_role == "conditional":
                    continue
                if producer_id not in dependency_ids:
                    dependency_ids.append(producer_id)
        return dependency_ids

    def _topological_order_steps(
        self,
        step_ids: set[str],
        *,
        step_map: dict[str, dict[str, Any]],
    ) -> list[str]:
        ordered: list[str] = []
        pending = set(step_ids)
        while pending:
            progressed = False
            for step_id in sorted(pending):
                deps = [
                    dep_id
                    for dep_id in self._resolve_planned_dependencies(
                        step_id,
                        step_map=step_map,
                        planned_step_ids=step_ids,
                    )
                    if dep_id in step_ids
                ]
                if all(dep_id in ordered for dep_id in deps):
                    ordered.append(step_id)
                    pending.remove(step_id)
                    progressed = True
                    break
            if not progressed:
                ordered.extend(sorted(pending))
                break
        return ordered

    def _reconcile_dependencies(self, todos: list[TodoItem]) -> list[TodoItem]:
        """Normalize initial todo statuses against their dependencies."""
        plan: TodoPlan = {
            "plan_version": "v1",
            "objective": "",
            "strategy": "rule_based_fallback",
            "missing_inputs": [],
            "reasoning_summary": "",
            "todos": todos,
        }
        refreshed = self.refresh_ready_todos(plan)
        return refreshed["todos"] if refreshed is not None else todos
